2012/09/09 13:30:02 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1044] Access denied for user 'mysite'@'localhost' to database 'mysite'' in /home/sites/mysite/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/sites/mysite/framework/db/CDbConnection.php(331): CDbConnection->open()
#1 /home/sites/mysite/framework/db/CDbConnection.php(309): CDbConnection->setActive(true)
#2 /home/sites/mysite/framework/base/CModule.php(388): CDbConnection->init()
#3 /home/sites/mysite/framework/base/CModule.php(104): CModule->getComponent('db')
#4 /home/sites/mysite/framework/gii/generators/model/ModelCode.php(57): CModule->__get('db')
#5 /home/sites/mysite/framework/web/CFormModel.php(40): ModelCode->init()
#6 /home/sites/mysite/framework/gii/CCodeGenerator.php(154): CFormModel->__construct()
#7 /home/sites/mysite/framework/gii/CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 /home/sites/mysite/framework/web/actions/CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 /home/sites/mysite/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /home/sites/mysite/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /home/sites/mysite/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/sites/mysite/framework/web/CWebApplication.php(283): CController->run('')
#13 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /home/sites/mysite/www/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model
HTTP_REFERER=http://mysite/index.php?r=gii/default/index
---
2012/09/09 13:32:29 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mysite.user' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `user`.
in /home/sites/mysite/www/index.php (13)
2012/09/09 13:36:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
2012/09/09 13:38:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
2012/09/09 13:38:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
2012/09/09 13:42:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
2012/09/09 13:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
2012/09/09 13:46:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
2012/09/09 16:58:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
2012/09/09 16:58:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "User".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('User')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=User
---
2012/09/09 17:04:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "User".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('User')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=User
---
2012/09/09 17:10:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "User".' in /home/sites/mysite/framework/web/CController.php:484
Stack trace:
#0 /home/sites/mysite/framework/web/CController.php(271): CController->missingAction('User')
#1 /home/sites/mysite/framework/web/CWebApplication.php(283): CController->run('User')
#2 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('site/User')
#3 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /home/sites/mysite/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/User
---
2012/09/09 17:10:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in /home/sites/mysite/framework/web/CController.php:484
Stack trace:
#0 /home/sites/mysite/framework/web/CController.php(271): CController->missingAction('user')
#1 /home/sites/mysite/framework/web/CWebApplication.php(283): CController->run('user')
#2 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('site/user')
#3 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /home/sites/mysite/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/user
---
2012/09/09 17:11:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /home/sites/mysite/framework/web/CWebApplication.php:287
Stack trace:
#0 /home/sites/mysite/framework/web/CWebApplication.php(142): CWebApplication->runController('user')
#1 /home/sites/mysite/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /home/sites/mysite/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=user
---
